# Generated by Django 4.2.3 on 2024-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunucu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='limit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='usage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
