# Generated by Django 4.2.3 on 2023-08-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_bakiye_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='hizmet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='musteri_soyad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='musteri_ad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
