# Generated by Django 4.2.3 on 2023-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_fatura_hizmet_fatura_musteri_soyad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy_number',
            name='proxy_n',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
