# Generated by Django 4.2.3 on 2023-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_ticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='processed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
