# Generated by Django 4.2.3 on 2023-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_ticket_processed_by_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
