# Generated by Django 4.2.3 on 2023-08-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxies',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
