# Generated by Django 4.2.3 on 2023-11-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_proxies_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Ticket_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('processed_by', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.ticket')),
            ],
        ),
    ]
