# Generated by Django 4.2.3 on 2023-11-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_remove_ticket_processed_by_remove_ticket_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_report',
            name='processed_by',
            field=models.CharField(max_length=100),
        ),
    ]
