# Generated by Django 4.2.3 on 2023-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxies',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
