# Generated by Django 4.2.3 on 2023-12-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_proxy_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
