# Generated by Django 4.2.3 on 2023-12-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_user_email_confirmed_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
